name: Java CI  # Puedes cambiar el nombre del flujo de trabajo según tu preferencia

on:
  push:
    branches:
      - master  # Puedes cambiar "main" por el nombre de tu rama principal si es diferente

jobs:
  build:
    runs-on: ubuntu-latest  # Puedes cambiar "ubuntu-latest" por otro sistema operativo si lo prefieres

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Puedes cambiar '11' por la versión de Java que estés utilizando en tu proyecto
          distribution: 'adopt'  # Ajusta esto según la distribución de Java que estás utilizando
          architecture: 'x64'

      - name: Check if Chrome is installed
        run: google-chrome --version || echo "Chrome is not installed"

      - name: Build with Maven
        run: mvn -B package --file pom.xml  # Si tu archivo pom.xml tiene un nombre diferente, cámbialo aquí

      - name: Run tests
        run: mvn -B test -Dcucumber.options="--tags @Prueba"  # Reemplaza @tu_etiqueta con la etiqueta que deseas ejecutar