name: Java CI  # Puedes cambiar el nombre del flujo de trabajo según tu preferencia

on:
  push:
    branches:
      - master  # Puedes cambiar "main" por el nombre de tu rama principal si es diferente

jobs:
  build:
    runs-on: ubuntu-latest  # Puedes cambiar "ubuntu-latest" por otro sistema operativo si lo prefieres

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Puedes cambiar '11' por la versión de Java que estés utilizando en tu proyecto

      - name: Build with Maven
        run: mvn -B package --file pom.xml  # Si tu archivo pom.xml tiene un nombre diferente, cámbialo aquí

      - name: Run tests
        run: mvn -B test  # Si necesitas configuraciones adicionales para ejecutar tus pruebas, puedes ajustarlas aquí
